#! /usr/bin/bash

echo "---------Wi-Fi Networks---------"
# netsh wlan show profiles name=* key="clear" | grep "Key" | awk '{$1=$2=$3=$4="";print $0}'
netsh wlan show profiles name=* key="clear" | grep -e "Name" | awk '{$1=$2="";print $0}'